theme = "onedark"

[editor]
#line-number = "relative"
#mouse = false
cursorline = true
#auto-pairs = true
#bufferline = "always"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

#[editor.statusline]
#left = ["mode", "spinner"]
#center = ["file-name"]
#right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
#separator = "│"
